config/routes.rb
# frozen_string_literal: true

# Application Routes
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  devise_scope :user do
    resources :sellers
  end

  resources :categories
  resources :brands
  resources :products
  resources :products do
    resources :comments
  end


  resource :carts
  resources :cart_items
  resources :orders
  resources :charges, only: %i[new create]


  get '/all_products', to: 'index#all_products', as: 'all_products'
  post '/apply_coupon', to: 'orders#apply_coupon', as: 'apply_coupon'
  get '/myorders', to: 'orders#myorders', as: 'myorders'
  get '/category_products/:slug', to: 'index#category_products', as: 'category_products'
  get '/brand_products/:slug', to: 'index#brand_products', as: 'brand_products'
  get '/decreament', to: 'cart_items#decreament'
  get '/increament', to: 'cart_items#increament'
  get '/remove_item', to: 'cart_items#remove_item'
  get '/unauthorized', to: 'index#unauthorized'
  get '/notfound', to: 'index#notfound'
  root 'index#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/brand.rb
# frozen_string_literal: true

# Brand model
class Brand < ApplicationRecord
  has_many :products
  validates :name, uniqueness: { message: 'Already exists' }
  before_save :add_slug

  def add_slug
    self.slug = name.parameterize
  end
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :cart_items
  belongs_to :user, optional: true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :cart
  belongs_to :product
end

app/models/category.rb
# frozen_string_literal: true

# Category ActiveRecord
class Category < ApplicationRecord
  has_many :products

  validates :name, uniqueness: { message: 'Already exists' }
  before_save :add_slug

  def add_slug
    self.slug = name.parameterize
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :product
end

app/models/coupon.rb
class Coupon < ApplicationRecord
  validates :code, presence: true
end

app/models/order.rb
class Order < ApplicationRecord
  enum status: %i[draft pending processing delivered]
  # attribute :status, :integer, default: 'draft'
  belongs_to :user
  has_many :order_items
  before_create :add_order_id

  def add_order_id
    self.order_id = 4.times.map { rand(65..90).chr }.join.to_s + 8.times.map { rand(0..10) }.join.to_s
  end
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  enum status: %i[draft pending processing delivered]
  belongs_to :order
  belongs_to :product
end

app/models/picture.rb
class Picture < ApplicationRecord
end

app/models/product.rb
# frozen_string_literal: true

# Product Active Record
class Product < ApplicationRecord
  enum status: %i[available outofstock draft]
  belongs_to :category
  belongs_to :brand
  belongs_to :user
  has_one_attached :main_image
  has_many_attached :images
  has_many :comments
  validates :description, length: { minimum: 50, message: ' must be greater than 50 characters' }
  before_save :add_slug
  before_create :add_sku
  def add_sku
    self.sku = 4.times.map { rand(65..90).chr }.join.to_s + 8.times.map { rand(0..10) }.join.to_s
  end

  def add_slug
    self.slug = name.parameterize + id.to_s
  end

end

app/models/role.rb
# frozen_string_literal: true

# Role Model
class Role < ApplicationRecord
  has_and_belongs_to_many :users, join_table: :users_roles

  belongs_to :resource,
             polymorphic: true,
             optional: true

  validates :resource_type,
            inclusion: { in: Rolify.resource_types },
            allow_nil: true

  scopify
end

app/models/user.rb
# frozen_string_literal: true

# USer Active Record
class User < ApplicationRecord
  attr_accessor :first_name, :last_name

  before_save :set_full_name
  before_save :set_default_avatar
  has_many :products
  has_many :orders
  has_one_attached :avatar
  has_one :cart
  rolify
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def set_full_name
    self.full_name = "#{@first_name} #{@last_name}"
  end

  def set_default_avatar
    unless avatar.attached?
      avatar.attach(io: File.open(Rails.root.join('app', 'assets', 'images', 'user.png')), filename: 'user.png',
                    content_type: 'image/png')
    end
  end

  def first_name
    full_name.split(' ')[0]
  end

  def last_name
    full_name.split(' ')[1]
  end

end

app/controllers/sellers_controller.rb
# frozen_string_literal: true

# This class manages seller registrations and add seller roles
class SellersController < Users::RegistrationsController
  def create
    super
    resource.add_role :seller
  end

  private

  def after_sign_up_path_for(_resource)
    root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/cartitems_helper.rb
module CartitemsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/sellers/new.html.erb
<div class="row">
<div class="col-md-4 offset-4">

<div class="card">
<div class="card-header">

<h2>Sign up</h2>

</div>

<div class="card-body">

<%= form_for(resource, as: resource_name, url: sellers_path) do |f| %>
  <%= render "devise/shared/error_messages", resource: resource %>

  <div class="form-group">
    <%= f.label :email %><br />
    <%= f.email_field :email, autofocus: true, autocomplete: "email", class: "form-control" %>
  </div>


  <div class="form-group">
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name, autofocus: true, autocomplete: "first_name", class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name, autofocus: true, autocomplete: "last_name", class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :password %>
    <% if @minimum_password_length %>
    <em>(<%= @minimum_password_length %> characters minimum)</em>
    <% end %><br />
    <%= f.password_field :password, autocomplete: "new-password", class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation, autocomplete: "new-password", class: "form-control" %>
  </div>
  <div class="actions">
    <%= f.submit "Sign up", class: "btn btn-primary" %>
  </div>
<% end %>

<%= render "devise/shared/links" %>

</div>
</div>
</div>
</div>