config/routes.rb
# frozen_string_literal: true

# Application Routes
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  devise_scope :user do
    resources :sellers
  end

  resources :categories
  resources :brands
  resources :products
  resources :products do
    resources :comments
  end


  resource :carts
  resources :cart_items
  resources :orders
  resources :charges, only: %i[new create]


  get '/all_products', to: 'index#all_products', as: 'all_products'
  post '/apply_coupon', to: 'orders#apply_coupon', as: 'apply_coupon'
  get '/myorders', to: 'orders#myorders', as: 'myorders'
  get '/category_products/:slug', to: 'index#category_products', as: 'category_products'
  get '/brand_products/:slug', to: 'index#brand_products', as: 'brand_products'
  get '/decreament', to: 'cart_items#decreament'
  get '/increament', to: 'cart_items#increament'
  get '/remove_item', to: 'cart_items#remove_item'
  get '/unauthorized', to: 'index#unauthorized'
  get '/notfound', to: 'index#notfound'
  root 'index#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/brand.rb
# frozen_string_literal: true

# Brand model
class Brand < ApplicationRecord
  has_many :products
  validates :name, uniqueness: { message: 'Already exists' }
  before_save :add_slug

  def add_slug
    self.slug = name.parameterize
  end
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :cart_items
  belongs_to :user, optional: true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :cart
  belongs_to :product
end

app/models/category.rb
# frozen_string_literal: true

# Category ActiveRecord
class Category < ApplicationRecord
  has_many :products

  validates :name, uniqueness: { message: 'Already exists' }
  before_save :add_slug

  def add_slug
    self.slug = name.parameterize
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :product
end

app/models/coupon.rb
class Coupon < ApplicationRecord
  validates :code, presence: true
end

app/models/order.rb
class Order < ApplicationRecord
  enum status: %i[draft pending processing delivered]
  # attribute :status, :integer, default: 'draft'
  belongs_to :user
  has_many :order_items
  before_create :add_order_id

  def add_order_id
    self.order_id = 4.times.map { rand(65..90).chr }.join.to_s + 8.times.map { rand(0..10) }.join.to_s
  end
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  enum status: %i[draft pending processing delivered]
  belongs_to :order
  belongs_to :product
end

app/models/picture.rb
class Picture < ApplicationRecord
end

app/models/product.rb
# frozen_string_literal: true

# Product Active Record
class Product < ApplicationRecord
  enum status: %i[available outofstock draft]
  belongs_to :category
  belongs_to :brand
  belongs_to :user
  has_one_attached :main_image
  has_many_attached :images
  has_many :comments
  validates :description, length: { minimum: 50, message: ' must be greater than 50 characters' }
  before_save :add_slug
  before_create :add_sku
  def add_sku
    self.sku = 4.times.map { rand(65..90).chr }.join.to_s + 8.times.map { rand(0..10) }.join.to_s
  end

  def add_slug
    self.slug = name.parameterize + id.to_s
  end

end

app/models/role.rb
# frozen_string_literal: true

# Role Model
class Role < ApplicationRecord
  has_and_belongs_to_many :users, join_table: :users_roles

  belongs_to :resource,
             polymorphic: true,
             optional: true

  validates :resource_type,
            inclusion: { in: Rolify.resource_types },
            allow_nil: true

  scopify
end

app/models/user.rb
# frozen_string_literal: true

# USer Active Record
class User < ApplicationRecord
  attr_accessor :first_name, :last_name

  before_save :set_full_name
  before_save :set_default_avatar
  has_many :products
  has_many :orders
  has_one_attached :avatar
  has_one :cart
  rolify
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def set_full_name
    self.full_name = "#{@first_name} #{@last_name}"
  end

  def set_default_avatar
    unless avatar.attached?
      avatar.attach(io: File.open(Rails.root.join('app', 'assets', 'images', 'user.png')), filename: 'user.png',
                    content_type: 'image/png')
    end
  end

  def first_name
    full_name.split(' ')[0]
  end

  def last_name
    full_name.split(' ')[1]
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/cartitems_helper.rb
module CartitemsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/index/all_products.html.erb
<div class="container-fluid">
<h2 class="text-center mt-5">All Products</h2>
<section class="product mt-5 mb-5">
<div class="row">
<div class="col-md-3">
<%= render 'shared/side_menu', categories: @categories, brands: @brands %>

</div>
<div class="col-md-9">
<div class="row">

<% if @products.count > 0 %>
  <% @products.each do |product|%>
    <%= render "shared/product", model: product %>
  <% end %>
  </div>
<% else %>
  <h4>No Products Found</h4>
<% end %>

</div>
</div>
</div>
</section>

app/views/index/index.html.erb
<%= render "shared/slider" %>
<div class="container-fluid">
<section class="product mt-5 mb-5">
<div class="row">
<div class="col-md-4">
<%= render 'shared/side_menu', categories: @categories, brands: @brands %>
</div>
<div class="col-md-8">
<div class="row">
<% @products.each do |product|%>
<%= render "shared/product", model: product %>
<% end %>
</div>

</div>
</div>
</div>
</section>

app/views/index/product.html.erb
<div class="container-fluid mt-2 mb-3">
	<div class="row no-gutters">
		<div class="col-md-5 pr-2">
			<div class="card">
				<div class="demo">

          <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>

<%  @product.images.each do |img,i| %>
    <li data-target="#carouselExampleIndicators" data-slide-to="<% i %>"></li>
<% end %>
  </ol>
  <div class="carousel-inner">

	 <% if @product.main_image.attached? %>
	 <div class="carousel-item active">
	 <%= image_tag @product.main_image, class: "d-block img-responsive img-fluid " %>
  </div>
  <% else %>
  <td><p>No image</p></td>
  <% end %>

<%  @product.images.each do |img| %>
	 <div class="carousel-item">
	 <%= image_tag img, class: "d-block img-responsive img-fluid " %>
	 </div>
<% end %>



  </div>
  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>
				</div>
			</div>
			<div class="card mt-2">
		<div class="comment-section" id="comment-section">
		<%= render @product.comments %>


	<div class="comment-form" id="new_comment">
	<%= form_with(model: [@product, @comment], remote: :true) do |f| %>
	<%= hidden_field_tag :authenticity_token, form_authenticity_token %>
		<%= f.label :content %><br>
		<%= f.text_area :content %>
		<%= f.submit %>
	<% end %>

					</div>
					<hr>
				</div>
			</div>
		</div>
		<div class="col-md-7">
			<div class="card">
				<div class="d-flex flex-row align-items-center">
					<div class="p-ratings"> <i class="fa fa-star"></i> <i class="fa fa-star"></i> <i class="fa fa-star"></i> <i class="fa fa-star"></i> </div> <span class="ml-1"></span> </div>
				<div class="about"> <span class="font-weight-bold"><%= @product.name %> </span>
					<h4 class="font-weight-bold"><%= number_to_currency(@product.price) %></h4> </div>
				<div class="buttons">
					<button class="btn btn-outline-warning btn-long cart" onclick="add_to_cart(<%= @product.id %>)">Add to Cart</button>
				</div>
				<hr>
				<div class="product-description">

					<div class="mt-2"> <span class="font-weight-bold">Description</span>
						<p><%= @product.description %></p>
					</div>
					<div class="mt-2"> <span class="font-weight-bold">Seller</span> </div>
					<div class="d-flex flex-row align-items-center"> <img src="https://i.imgur.com/N2fYgvD.png" class="rounded-circle store-image">
						<div class="d-flex flex-column ml-1 comment-profile">
							<div class="comment-ratings"> <i class="fa fa-star"></i> <i class="fa fa-star"></i> <i class="fa fa-star"></i> <i class="fa fa-star"></i> </div> <span class="username"><%= @product.user.full_name %></span></div>
					</div>
				</div>
			</div>

		</div>
	</div>
</div>

app/views/layouts/_menu.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Products</a>
      </li>
       <li class="nav-item">
        <a class="nav-link" href="#">New Arrivals</a>
      </li>


    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
     <ul class="navbar-nav ml-auto">
      <li class="nav-item">
      <%  if user_signed_in? %>
       <%= button_to "logout", destroy_user_session_path, method: :delete, class: "btn btn-warning" %>
      </li>
      <% else %>
       <li class="nav-item">

        <a href="/users/sign_in" class="btn btn-primary">Login</a>
       </li>

        <li class="nav-item">

        <%= link_to "Become Seller", new_seller_path, class: "btn btn-success ml-2" %>
       </li>
      <% end %>
      <ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ecommerce</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>


    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

  </head>

  <body>
  <%= render "shared/menu" %>
    <%= yield %>
        <%= javascript_pack_tag 'application' %>
<%# <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload', "type": "module" %> %>
  </body>
</html>

app/views/shared/_error.html.erb
<% if model.errors.any? %>
  <div id="error_explanation">
    <p class="text text-warning"><%= pluralize(model.errors.count, "error") %> prohibited this article from being saved:</p>

    <ul class="text text-danger">
      <% model.errors.each do |error| %>
        <li ><%= error.full_message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_menu.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
      <%= link_to "Navbar", root_path, class: "navbar-brand" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
     <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
          <%= link_to "Home", root_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Products", all_products_path, class: "nav-link" %>
      </li>
        <li class="nav-item">
          <%= link_to "Cart", carts_path, class: "nav-link" %>
      </li>
    </ul>
     <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ml-auto mb-2 mb-lg-0">

      <%  if user_signed_in? %>

        <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
       <div class="profile-img">
       <%# <% if current_user.avatar %>
        <%# <%= image_tag current_user.avatar, class: "rounded-circle", style: "width: 20px; height:20px" %>
        <%# <% end %>
       </div>
          <%=  current_user.full_name %>
        </a>
        <% if current_user.has_role? :seller %>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%= link_to "Products", products_path, class: "dropdown-item" %>
            <%= link_to "Categories", categories_path, class: "dropdown-item" %>
            <%= link_to "Brands", brands_path, class: "dropdown-item" %>
            <%= link_to "Orders", orders_path, class: "dropdown-item" %>
            <%= link_to "My Orders", myorders_path, class: "dropdown-item" %>
            <%= link_to "Profile", edit_user_registration_path() , class: "dropdown-item" %>
          </div>
        <% else %>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%= link_to "My Orders", myorders_path, class: "dropdown-item" %>
          </div>
        <% end %>
      </li>
      <li class="nav-item">
        <%= button_to "logout", destroy_user_session_path, method: :delete, class: "btn btn-warning" %>
      </li>
      <% else %>
       <li class="nav-item">

        <a href="/users/sign_in" class="btn btn-primary">Login</a>
       </li>

        <li class="nav-item">

        <%= link_to "Become Seller", new_seller_path, class: "btn btn-success mr-2" %>
       </li>
      <% end %>
      </ul>

    </div>
  </div>
</nav>

app/views/shared/_product.html.erb
<div class="col-md-4">
<div class="card">
 <% if model.main_image.attached? %>
  <%= image_tag model.main_image, class: "card-img-top w-100", style: "height:15vw;object-fit:cover" %>
  <% else %>
  <td><p>No image</p></td>
  <% end %>
    <div class="card-body">
      <h5 class="card-title"><%= model.name %></h5>
      <p class="card-text"><%=  model.description.truncate(20) %></p>
      <p class="card-text"><small class="text">Category : <%=  model.category.name %></small></p>
      <p class="card-text"><small class="text">Brand : <%= model.brand.name %></small></p><% model.brand.name %></small></p>
      <button class="btn btn-success btn-sm" onclick="add_to_cart(<%= model.id %>)">Add to cart</button>
      <%= link_to "View", product_path(model.slug), class: "btn btn-success btn-sm" %>
    </div>
  </div>
</div>

app/views/shared/_seller_menu.html.erb
<div class="row mt-5">
<div class="col-md-2">
<div class="nav flex-column nav-pills bg-light" id="v-pills-tab" role="tablist" aria-orientation="vertical">
  <a class="nav-link" id="v-pills-home-tab" href="/products"  aria-controls="v-pills-home" aria-selected="true">Manage Products</a>
  <a class="nav-link" id="v-pills-profile-tab" href="/brands"  aria-controls="v-pills-profile" aria-selected="false">Manage Brands</a>
  <a class="nav-link" id="v-pills-profile-tab"  href="/categories" aria-controls="v-pills-profile" aria-selected="false">Manage Categories</a>
  <a class="nav-link" id="v-pills-settings-tab"  href="/orders" aria-controls="v-pills-settings" aria-selected="false">Manage Orders</a>
</div>


</div>

app/views/shared/_side_menu.html.erb
<div class="card" style="width: 22rem;">
  <div class="card-header">
    Categories
  </div>
  <ul class="list-group list-group-flush">
  <% categories.each do |category| %>
    <%= link_to category.name , category_products_path(category.slug),  class: "list-group-item"  %>
  <% end %>
  </ul>
</div>

<div class="card mt-5" style="width: 22rem;">
  <div class="card-header">
    Brands
  </div>
  <ul class="list-group list-group-flush">
    <% brands.each do |brand| %>
      <%= link_to brand.name , brand_products_path(brand.slug),  class: "list-group-item"  %>
    <% end %>
  </ul>
</div>

app/views/shared/_slider.html.erb
<section class="slider">
<div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img class="d-block w-100 h-80" src="https://icms-image.slatic.net/images/ims-web/0dcb3146-c623-40ca-884d-b48b946ab55e.png" alt="First slide">
    </div>
    <div class="carousel-item">
      <img class="d-block w-100 h-80" src="https://icms-image.slatic.net/images/ims-web/9803fb25-6908-457d-bca7-138267c69d13.png" alt="Second slide">
    </div>
    <div class="carousel-item">
      <img class="d-block w-100 h-80" src="https://icms-image.slatic.net/images/ims-web/f88ca640-0358-44a7-b066-3a2fd70ef3bc.jpg" alt="Third slide">
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>
</section>